wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1648613238
    t:
      1:
      - 1
      - 5
      3:
      - 16
      4: 3.8.10
      5: 0.12.10
      8:
      - 5
batch_size:
  desc: null
  value: 2
channel_dims:
  desc: null
  value: 1
cross_entropy_weight:
  desc: null
  value: 0.095
epochs:
  desc: null
  value: 90
fit_steps:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.01
loss_func:
  desc: null
  value: WCE
start_filters:
  desc: null
  value: 64
