# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q2z8e03Ks1S2BSCndJTXULzghcl0RcxE
"""

import torch
import numpy as np


def predict(img,
            model,
            preprocess,
            postprocess,
            device,
            ):
    model.eval()
    img = preprocess(img)  # preprocess image
    x = torch.from_numpy(img).to(device)  # to torch, send to device
    with torch.no_grad():
        out = model(x)  # send through model/network

    # out_softmax = torch.softmax(out, dim=1)  # perform softmax on outputs
    result = postprocess(out)  # postprocess outputs

    return result