wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.8
    start_time: 1646416617
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 16
      4: 3.8.8
      5: 0.12.10
      8:
      - 2
      - 5
cross_entropy_weight:
  desc: null
  value: 0.045
epochs:
  desc: null
  value: 40
fit_steps:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.01
